/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.ucieffe.kata.salestaxes;

import org.ucieffe.kata.salestaxes.model.Basket;
import org.ucieffe.kata.salestaxes.model.Item;
import org.ucieffe.kata.salestaxes.model.Report;

import java.math.BigDecimal;

import static java.util.stream.Collectors.reducing;

public class Calculator {


    public Report calculateTotal(Basket basket) {
        BigDecimal total = basket.getItemList().stream()
                .map(Item::getPrice)
                .map(BigDecimal::new)
                .collect(reducing((i1, i2) -> i1.add(i2)))
                .orElse(new BigDecimal("0.00"));
        return new Report(basket, new BigDecimal("0.00"), total);
    }
}
