/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.ucieffe.kata.salestaxes;

import java.math.BigDecimal;

public class Calculator {

    private final Item item;

    public Calculator(Item item) {
        this.item = item;
    }

    public BigDecimal calculateTotal() {
        if(item == null)
            return new BigDecimal("0.00");
        return item.getPrice();
    }

}
