/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.ucieffe.kata.salestaxes;

import java.math.BigDecimal;

public class SalesTaxes {

    public BigDecimal calculateTotal() {
        return new BigDecimal("0.00");
    }
}
