/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.ucieffe.kata.salestaxes;

import org.junit.Before;
import org.junit.Test;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import static java.util.Arrays.asList;
import static java.util.Collections.emptyList;
import static org.hamcrest.core.Is.is;
import static org.junit.Assert.assertThat;

public class CalculatorTest {

    private Calculator calculator;

    @Before
    public void setUp() throws Exception {
        calculator = new Calculator();
    }

    @Test
    public void return_zero_when_no_item() {
        assertThat(new BigDecimal("0.00"), is(calculator.calculateTotal(emptyList()).getTotal()));
    }

    @Test
    public void return_item_price_when_add_one_item_with_exemption() {
        assertThat(new BigDecimal("1.10"), is(calculator.calculateTotal(asList(new Item("1.10"))).getTotal()));
    }

    @Test
    public void return_sum_price_when_add_more_than_one_item_with_exemption() {
        List<Item> itemList = asList(
                new Item("1.10"),
                new Item("2.20"),
                new Item("3.30")
        );

        assertThat(new BigDecimal("6.60"), is(calculator.calculateTotal(itemList).getTotal()));
    }

}
