/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.ucieffe.kata.salestaxes;

import org.junit.Test;

import java.math.BigDecimal;

import static org.hamcrest.core.Is.is;
import static org.junit.Assert.*;

public class SalesTaxesTest {

    @Test
    public void return_zero_when_no_item() {
        SalesTaxes salesTaxes = new SalesTaxes();

        assertThat(new BigDecimal("0.00"), is(salesTaxes.calculateTotal()));
    }
}
